import type { ItemTier, RankedItem } from "@/types/countdown";

export type DataSourceProvider = {
  id: string;
  label: string;
  load: () => Promise<RankedItem[]>;
};

function tierForRank(rank: number, total: number): ItemTier {
  const highCut = Math.ceil(total * 0.33);
  const midCut = Math.ceil(total * 0.66);
  if (rank <= highCut) return "high";
  if (rank <= midCut) return "mid";
  return "low";
}

/** 考研高频词汇（示例子集，结构可扩展至全量 5500） */
const KAOYAN_WORDS: string[] = [
  "abandon", "ability", "abroad", "absence", "absolute", "absorb", "abstract",
  "abundant", "academic", "accept", "access", "accident", "accompany", "accomplish",
  "account", "accurate", "achieve", "acknowledge", "acquire", "adapt", "adequate",
  "adjust", "administration", "admire", "admit", "adopt", "adult", "advance",
  "advantage", "adventure", "advertise", "advice", "advocate", "affair", "affect",
  "afford", "afraid", "agency", "agenda", "agent", "aggressive", "agree", "agriculture",
  "ahead", "aid", "aim", "aircraft", "alarm", "album", "alcohol", "alert", "alien",
  "alike", "alive", "alliance", "allow", "almost", "alone", "along", "alter",
  "alternative", "although", "altogether", "amateur", "amaze", "ambition", "ambitious",
  "amend", "amount", "ample", "analyse", "analysis", "ancestor", "ancient", "anger",
  "angle", "anniversary", "announce", "annual", "anticipate", "anxiety", "anxious",
  "apart", "apartment", "apologize", "apparent", "appeal", "appear", "appetite",
  "applaud", "apply", "appoint", "appreciate", "approach", "appropriate", "approve",
  "approximate", "architect", "architecture", "argue", "argument", "arise", "army",
  "arrange", "arrest", "arrival", "article", "artificial", "artist", "aspect",
  "assemble", "assert", "assess", "asset", "assign", "assist", "associate", "assume",
  "assure", "atmosphere", "attach", "attack", "attempt", "attend", "attention",
  "attitude", "attract", "attribute", "audience", "author", "authority", "automatic",
  "available", "average", "avoid", "award", "aware", "background", "balance", "barrier",
  "basic", "basis", "behalf", "behave", "behavior", "belief", "belong", "benefit",
  "besides", "betray", "beyond", "billion", "biology", "birth", "blame", "blank",
  "block", "blood", "board", "bond", "border", "borrow", "bother", "boundary",
  "branch", "brand", "breath", "brief", "brilliant", "broadcast", "budget", "build",
  "bureau", "burst", "business", "calculate", "campaign", "campus", "cancel",
  "candidate", "capable", "capacity", "capital", "capture", "career", "careful",
  "carrier", "category", "cause", "celebrate", "cell", "central", "century", "ceremony",
  "certain", "challenge", "champion", "channel", "chapter", "character", "charge",
  "charity", "chart", "chase", "chemical", "chief", "childhood", "choice", "choose",
  "circuit", "circumstance", "cite", "citizen", "civil", "claim", "classic", "classify",
  "clause", "client", "climate", "clinic", "closely", "clue", "coach", "code",
  "collapse", "colleague", "collect", "college", "combine", "comfort", "command",
  "comment", "commerce", "commission", "commit", "committee", "common", "communicate",
  "community", "company", "compare", "compete", "complain", "complete", "complex",
  "component", "compose", "compound", "comprehensive", "comprise", "compute",
  "concentrate", "concept", "concern", "conclude", "concrete", "conduct", "conference",
  "confidence", "confirm", "conflict", "confuse", "connect", "conquer", "conscious",
  "consensus", "consent", "consequence", "conservative", "consider", "consist",
  "consistent", "constant", "constitute", "construct", "consult", "consume", "contact",
  "contain", "contemporary", "content", "contest", "context", "continue", "contract",
  "contrast", "contribute", "control", "controversy", "convention", "convert",
  "convince", "cooperate", "coordinate", "cope", "core", "corporate", "correct",
  "correspond", "cost", "council", "counsel", "counter", "country", "county", "couple",
  "courage", "course", "court", "cover", "craft", "crash", "create", "creative",
  "creature", "credit", "criminal", "crisis", "criterion", "critical", "criticize",
  "crucial", "culture", "curious", "current", "curriculum", "custom", "cycle",
  "damage", "danger", "database", "debate", "decade", "decide", "declare", "decline",
  "decrease", "dedicate", "defeat", "defend", "define", "definite", "degree",
  "delay", "deliberate", "deliver", "demand", "democracy", "demonstrate", "deny",
  "depart", "depend", "depict", "deploy", "deposit", "depress", "derive", "describe",
  "desert", "deserve", "design", "desire", "despite", "destroy", "detail", "detect",
  "determine", "develop", "device", "devote", "diagram", "dialogue", "differ",
  "digital", "dimension", "direct", "direction", "director", "disappear", "disaster",
  "discipline", "discover", "discuss", "disease", "display", "dispose", "distinct",
  "distinguish", "distribute", "district", "disturb", "diverse", "divide", "division",
  "document", "domestic", "dominate", "double", "doubt", "draft", "dramatic", "draw",
  "dream", "drive", "due", "duration", "dynamic", "eager", "earn", "earth", "ease",
  "economic", "economy", "edge", "edit", "edition", "effect", "effective", "efficient",
  "effort", "element", "eliminate", "elsewhere", "embrace", "emerge", "emotion",
  "emphasis", "employ", "enable", "encounter", "encourage", "energy", "enforce",
  "engage", "engine", "engineer", "enhance", "enormous", "ensure", "enterprise",
  "entire", "entity", "environment", "episode", "equal", "equip", "equivalent",
  "error", "escape", "especially", "essential", "establish", "estate", "estimate",
  "ethic", "evaluate", "event", "eventually", "evidence", "evident", "evolution",
  "evolve", "exact", "examine", "example", "exceed", "excellent", "except", "exchange",
  "excite", "exclude", "excuse", "execute", "exercise", "exhaust", "exhibit", "exist",
  "expand", "expect", "expense", "experience", "experiment", "expert", "explain",
  "explode", "explore", "export", "expose", "express", "extend", "extent", "external",
  "extra", "extract", "extreme", "facility", "factor", "faculty", "fail", "fair",
  "faith", "fall", "false", "familiar", "family", "famous", "fancy", "fantasy",
  "fashion", "fast", "fatal", "fault", "favor", "feature", "federal", "fee",
  "feedback", "feel", "female", "fence", "festival", "fetch", "fever", "few",
  "fiber", "fiction", "field", "fierce", "figure", "file", "fill", "film", "final",
  "finance", "financial", "finding", "fine", "finger", "finish", "firm", "first",
  "fish", "fit", "fix", "flag", "flame", "flash", "flat", "flavor", "flee", "flexible",
  "flight", "float", "flood", "floor", "flow", "flower", "focus", "fold", "folk",
  "follow", "force", "forecast", "foreign", "forest", "forever", "forget", "form",
  "formal", "format", "former", "formula", "forth", "fortune", "forward", "found",
  "foundation", "frame", "framework", "free", "freedom", "freeze", "frequency",
  "frequent", "fresh", "friend", "friendly", "friendship", "frighten", "front",
  "fruit", "fuel", "fulfill", "full", "function", "fund", "fundamental", "funeral",
  "funny", "furniture", "further", "future", "gain", "gallery", "game", "gap",
  "garage", "garden", "gas", "gate", "gather", "gender", "gene", "general", "generate",
  "generous", "genius", "gentle", "genuine", "gesture", "giant", "gift", "girl",
  "give", "glad", "global", "glory", "goal", "gold", "good", "govern", "government",
  "grab", "grade", "gradual", "graduate", "grain", "grand", "grant", "graph",
  "grasp", "grass", "grateful", "grave", "great", "green", "greet", "ground", "group",
  "grow", "growth", "guarantee", "guard", "guess", "guest", "guide", "guilty",
  "habit", "handle", "hang", "happen", "happy", "hard", "hardly", "harm", "harmony",
  "harsh", "harvest", "hate", "have", "head", "headline", "health", "healthy",
  "hear", "heart", "heat", "heavy", "height", "hell", "help", "helpful", "hence",
  "hero", "hide", "high", "highlight", "highly", "highway", "hill", "hint", "hire",
  "historical", "history", "hit", "hold", "hole", "holiday", "hollow", "holy",
  "home", "honest", "honor", "hope", "horizon", "horror", "horse", "hospital",
  "host", "hot", "hotel", "hour", "house", "household", "housing", "however", "huge",
  "human", "humor", "hundred", "hunger", "hunt", "hurt", "husband", "hypothesis",
  "ice", "idea", "ideal", "identify", "identity", "ignore", "ill", "illegal",
  "illness", "illustrate", "image", "imagine", "immediate", "immigrant", "impact",
  "implement", "imply", "import", "important", "impose", "impossible", "impress",
  "improve", "incentive", "incident", "include", "income", "incorporate", "increase",
  "indeed", "independent", "index", "indicate", "individual", "industrial",
  "industry", "infant", "infect", "inflation", "influence", "inform", "information",
  "ingredient", "initial", "initiative", "injure", "inner", "innocent", "innovation",
  "input", "inquiry", "inside", "insight", "insist", "inspect", "inspire", "install",
  "instance", "instant", "instead", "institute", "institution", "instruction",
  "instrument", "insurance", "integrate", "integrity", "intellectual", "intelligence",
  "intend", "intense", "intention", "interact", "interest", "interface", "internal",
  "international", "Internet", "interpret", "interrupt", "interval", "interview",
  "introduce", "invest", "investigate", "investment", "invite", "involve", "iron",
  "island", "isolate", "issue", "item", "jail", "joint", "journal", "journey", "joy",
  "judge", "judgment", "jump", "junior", "jury", "justice", "justify", "keen", "keep",
  "key", "kick", "kid", "kill", "kind", "king", "kiss", "kitchen", "knee", "knife",
  "knock", "know", "knowledge", "label", "labor", "lack", "lady", "lake", "land",
  "landscape", "language", "large", "last", "late", "later", "latter", "laugh",
  "launch", "law", "lawyer", "lay", "layer", "lead", "leader", "leadership", "leading",
  "leaf", "league", "learn", "least", "leave", "lecture", "left", "legal", "legend",
  "legislation", "legitimate", "leisure", "lend", "length", "less", "lesson", "let",
  "letter", "level", "liberal", "library", "license", "lie", "life", "lift", "light",
  "like", "likely", "limit", "line", "link", "list", "listen", "literary", "literature",
  "little", "live", "living", "load", "loan", "local", "locate", "location", "lock",
  "logic", "logical", "lonely", "long", "look", "loose", "lose", "loss", "lost",
  "lot", "loud", "love", "lovely", "low", "lower", "luck", "lucky", "lunch", "machine",
  "mad", "magazine", "magic", "mail", "main", "mainly", "maintain", "major", "majority",
  "make", "male", "mall", "manage", "management", "manager", "manner", "manufacture",
  "many", "map", "march", "margin", "mark", "market", "marriage", "marry", "mass",
  "massive", "master", "match", "material", "math", "matter", "maximum", "maybe",
  "mayor", "meal", "mean", "meaning", "meanwhile", "measure", "mechanism", "media",
  "medical", "medicine", "medium", "meet", "meeting", "member", "membership", "memory",
  "mental", "mention", "menu", "mere", "merely", "mess", "message", "metal", "method",
  "middle", "might", "mile", "military", "milk", "mind", "mine", "minimum", "minister",
  "minor", "minority", "minute", "mirror", "miss", "mission", "mistake", "mix", "mixture",
  "mobile", "mode", "model", "moderate", "modern", "modest", "modify", "moment",
  "money", "monitor", "month", "mood", "moral", "more", "moreover", "morning", "most",
  "mostly", "mother", "motion", "motivate", "motivation", "motor", "mount", "mountain",
  "mouse", "mouth", "move", "movement", "movie", "much", "multiple", "murder", "muscle",
  "museum", "music", "must", "mutual", "mystery", "myth", "nail", "name", "narrative",
  "narrow", "nation", "national", "native", "natural", "nature", "near", "nearby",
  "nearly", "necessary", "neck", "need", "negative", "negotiate", "neighbor",
  "neighborhood", "neither", "nerve", "nervous", "network", "never", "nevertheless",
  "new", "news", "newspaper", "next", "nice", "night", "nobody", "noise", "none",
  "nor", "normal", "normally", "north", "northern", "nose", "not", "note", "nothing",
  "notice", "notion", "novel", "now", "nowhere", "nuclear", "number", "numerous",
  "nurse", "object", "objective", "obligation", "observe", "obtain", "obvious",
  "occasion", "occupy", "occur", "ocean", "odd", "of", "off", "offense", "offer",
  "office", "officer", "official", "often", "oil", "old", "on", "once", "one",
  "ongoing", "online", "only", "open", "operate", "operation", "opinion", "opponent",
  "opportunity", "oppose", "opposite", "option", "or", "oral", "order", "ordinary",
  "organ", "organic", "organization", "organize", "origin", "original", "other",
  "otherwise", "ought", "our", "out", "outcome", "outdoor", "outer", "output",
  "outside", "outstanding", "over", "overall", "overcome", "overlap", "overlook",
  "overnight", "overseas", "overwhelm", "owe", "own", "owner", "pace", "pack",
  "package", "page", "pain", "painful", "paint", "painter", "painting", "pair",
  "palace", "pale", "panel", "panic", "paper", "paragraph", "parallel", "parent",
  "park", "part", "participant", "participate", "particular", "particularly",
  "partly", "partner", "party", "pass", "passage", "passenger", "passion", "past",
  "patch", "path", "patient", "pattern", "pause", "pay", "payment", "peace", "peak",
  "peer", "penalty", "people", "per", "perceive", "percent", "percentage", "perception",
  "perfect", "perform", "performance", "perhaps", "period", "permanent", "permission",
  "permit", "person", "personal", "personality", "personally", "personnel", "perspective",
  "persuade", "phase", "phenomenon", "philosophy", "phone", "photo", "photograph",
  "phrase", "physical", "physician", "pick", "picture", "piece", "pile", "pilot",
  "pin", "pink", "pipe", "pitch", "place", "plain", "plan", "plane", "planet",
  "planning", "plant", "plastic", "plate", "platform", "play", "player", "pleasant",
  "please", "pleasure", "plenty", "plot", "plus", "pocket", "poem", "poet", "poetry",
  "point", "pole", "police", "policy", "political", "politician", "politics", "poll",
  "pollution", "pool", "poor", "pop", "popular", "population", "port", "portion",
  "portrait", "portray", "pose", "position", "positive", "possess", "possibility",
  "possible", "possibly", "post", "pot", "potato", "potential", "pound", "pour",
  "poverty", "powder", "power", "powerful", "practical", "practice", "praise",
  "pray", "precise", "predict", "prefer", "preference", "pregnant", "preparation",
  "prepare", "prescription", "presence", "present", "presentation", "preserve",
  "president", "press", "pressure", "pretend", "pretty", "prevent", "previous",
  "previously", "price", "pride", "priest", "primarily", "primary", "prime", "principal",
  "principle", "print", "prior", "priority", "prison", "prisoner", "privacy", "private",
  "probably", "problem", "procedure", "proceed", "process", "produce", "product",
  "production", "profession", "professional", "professor", "profile", "profit",
  "program", "progress", "project", "prominent", "promise", "promote", "prompt",
  "proof", "proper", "properly", "property", "proportion", "proposal", "propose",
  "prospect", "protect", "protection", "protein", "protest", "proud", "prove",
  "provide", "provider", "province", "provision", "psychological", "public",
  "publication", "publish", "pull", "punishment", "purchase", "pure", "purpose",
  "pursue", "push", "put", "qualify", "quality", "quarter", "question", "quick",
  "quickly", "quiet", "quite", "quote", "race", "racial", "radical", "radio",
  "rail", "rain", "raise", "range", "rank", "rapid", "rapidly", "rare", "rarely",
  "rate", "rather", "rating", "ratio", "raw", "reach", "react", "reaction", "read",
  "reader", "reading", "ready", "real", "realistic", "reality", "realize", "really",
  "reason", "reasonable", "recall", "receive", "recent", "recently", "recipe",
  "recognize", "recommend", "record", "recover", "recovery", "recruit", "red",
  "reduce", "reduction", "refer", "reference", "reflect", "reflection", "reform",
  "refugee", "refuse", "regard", "regarding", "regardless", "regime", "region",
  "regional", "register", "regular", "regularly", "regulate", "regulation", "reject",
  "relate", "relation", "relationship", "relative", "relatively", "relax", "release",
  "relevant", "relief", "religion", "religious", "reluctant", "rely", "remain",
  "remark", "remarkable", "remember", "remind", "remote", "remove", "repeat",
  "replace", "reply", "report", "reporter", "represent", "representation",
  "representative", "republic", "reputation", "request", "require", "requirement",
  "rescue", "research", "researcher", "resemble", "reservation", "reserve",
  "resident", "resist", "resolution", "resolve", "resort", "resource", "respect",
  "respond", "response", "responsibility", "responsible", "rest", "restaurant",
  "restore", "restrict", "restriction", "result", "retain", "retire", "return",
  "reveal", "revenue", "review", "revolution", "reward", "rhythm", "rice", "rich",
  "rid", "ride", "right", "ring", "rise", "risk", "river", "road", "robot", "rock",
  "role", "roll", "romantic", "roof", "room", "root", "rope", "rose", "rough",
  "round", "route", "routine", "row", "royal", "rub", "rule", "run", "rural",
  "rush", "sad", "safe", "safety", "sail", "sake", "salary", "sale", "salt",
  "same", "sample", "sanction", "sand", "satellite", "satisfaction", "satisfy",
  "save", "saving", "say", "scale", "scan", "scandal", "scare", "scenario", "scene",
  "schedule", "scheme", "scholar", "scholarship", "school", "science", "scientific",
  "scientist", "scope", "score", "scream", "screen", "script", "sea", "search",
  "season", "seat", "second", "secret", "secretary", "section", "sector", "secure",
  "security", "see", "seed", "seek", "seem", "segment", "select", "selection",
  "self", "sell", "senate", "senator", "send", "senior", "sense", "sensitive",
  "sentence", "separate", "sequence", "series", "serious", "seriously", "serve",
  "service", "session", "set", "setting", "settle", "settlement", "several",
  "severe", "sex", "sexual", "shade", "shadow", "shake", "shall", "shape", "share",
  "sharp", "she", "sheet", "shelf", "shell", "shelter", "shift", "shine", "ship",
  "shirt", "shock", "shoe", "shoot", "shop", "shopping", "shore", "short", "shortly",
  "shot", "should", "shoulder", "shout", "show", "shower", "shrink", "shut", "sick",
  "side", "sight", "sign", "signal", "significance", "significant", "significantly",
  "silence", "silent", "silver", "similar", "similarly", "simple", "simply", "sin",
  "since", "sing", "singer", "single", "sink", "sir", "sister", "sit", "site",
  "situation", "size", "skill", "skin", "sky", "slave", "sleep", "slice", "slide",
  "slight", "slightly", "slow", "slowly", "small", "smart", "smell", "smile",
  "smoke", "smooth", "snap", "snow", "so", "so-called", "soccer", "social", "society",
  "soft", "software", "soil", "solar", "soldier", "solid", "solution", "solve",
  "some", "somebody", "somehow", "someone", "something", "sometimes", "somewhat",
  "somewhere", "son", "song", "soon", "sophisticated", "sort", "soul", "sound",
  "source", "south", "southern", "space", "Spanish", "speak", "speaker", "special",
  "specialist", "species", "specific", "specifically", "speech", "speed", "spend",
  "spirit", "spiritual", "split", "spokesman", "sport", "spot", "spread", "spring",
  "square", "squeeze", "stability", "stable", "staff", "stage", "stain", "stake",
  "stand", "standard", "standing", "star", "stare", "start", "state", "statement",
  "station", "statistics", "status", "stay", "steady", "steal", "steel", "step",
  "stick", "still", "stimulate", "stock", "stomach", "stone", "stop", "storage",
  "store", "storm", "story", "straight", "strange", "stranger", "strategic",
  "strategy", "stream", "street", "strength", "strengthen", "stress", "stretch",
  "strike", "string", "strip", "stroke", "strong", "strongly", "structure", "struggle",
  "student", "studio", "study", "stuff", "stupid", "style", "subject", "submit",
  "subsequent", "substance", "substantial", "succeed", "success", "successful",
  "such", "sudden", "suddenly", "suffer", "sufficient", "sugar", "suggest", "suggestion",
  "suicide", "suit", "suitable", "sum", "summary", "summer", "summit", "sun",
  "super", "supply", "support", "supporter", "suppose", "sure", "surely", "surface",
  "surgery", "surprise", "surprised", "surprising", "surround", "survey", "survival",
  "survive", "survivor", "suspect", "sustain", "swear", "sweep", "sweet", "swim",
  "swing", "switch", "symbol", "symptom", "system", "table", "tackle", "tail",
  "take", "tale", "talent", "talk", "tall", "tank", "tap", "tape", "target",
  "task", "taste", "tax", "taxi", "tea", "teach", "teacher", "teaching", "team",
  "tear", "technical", "technique", "technology", "teen", "teenager", "telephone",
  "tell", "temperature", "temple", "temporary", "ten", "tend", "tendency", "tennis",
  "tension", "tent", "term", "terms", "terrible", "territory", "terror", "terrorism",
  "terrorist", "test", "testify", "testimony", "testing", "text", "than", "thank",
  "thanks", "that", "the", "theater", "their", "them", "theme", "themselves",
  "then", "theory", "therapy", "there", "therefore", "these", "they", "thick",
  "thin", "thing", "think", "thinking", "third", "thirty", "this", "those", "though",
  "thought", "thousand", "threat", "threaten", "three", "throat", "through",
  "throughout", "throw", "thumb", "thus", "ticket", "tie", "tight", "time", "tiny",
  "tip", "tire", "tired", "tissue", "title", "to", "tobacco", "today", "toe",
  "together", "toilet", "tolerance", "tomorrow", "tone", "tongue", "tonight",
  "too", "tool", "tooth", "top", "topic", "total", "totally", "touch", "tough",
  "tour", "tourist", "tournament", "toward", "towards", "tower", "town", "toy",
  "trace", "track", "trade", "tradition", "traditional", "traffic", "tragedy",
  "trail", "train", "training", "transfer", "transform", "transformation",
  "transition", "translate", "transport", "transportation", "trap", "trash",
  "travel", "treat", "treatment", "treaty", "tree", "tremendous", "trend", "trial",
  "tribe", "trick", "trip", "troop", "trouble", "truck", "true", "truly", "trust",
  "truth", "try", "tube", "tune", "tunnel", "turn", "TV", "twelve", "twenty",
  "twice", "twin", "two", "type", "typical", "typically", "ugly", "ultimate",
  "ultimately", "unable", "uncle", "under", "undergo", "understand", "understanding",
  "unemployment", "unexpected", "unfair", "unfortunately", "uniform", "union",
  "unique", "unit", "United", "universal", "universe", "university", "unknown",
  "unless", "unlike", "unlikely", "until", "unusual", "up", "update", "upon",
  "upper", "urban", "urge", "urgent", "us", "use", "used", "useful", "user", "usual",
  "usually", "utility", "vacation", "valley", "valuable", "value", "variable",
  "variation", "variety", "various", "vary", "vast", "vegetable", "vehicle", "venture",
  "version", "versus", "very", "vessel", "veteran", "via", "victim", "victory",
  "video", "view", "viewer", "village", "violence", "violent", "virtually",
  "virtue", "virus", "visible", "vision", "visit", "visitor", "visual", "vital",
  "voice", "volume", "volunteer", "vote", "voter", "vs", "vulnerable", "wage",
  "wait", "wake", "walk", "wall", "wander", "want", "war", "warm", "warn", "warning",
  "wash", "waste", "watch", "water", "wave", "way", "we", "weak", "wealth", "wealthy",
  "weapon", "wear", "weather", "wedding", "week", "weekend", "weekly", "weigh",
  "weight", "welcome", "welfare", "well", "west", "western", "what", "whatever",
  "wheel", "when", "whenever", "where", "whereas", "wherever", "whether", "which",
  "while", "whisper", "white", "who", "whole", "whom", "whose", "why", "wide",
  "widely", "widespread", "wife", "wild", "will", "willing", "win", "wind",
  "window", "wine", "wing", "winner", "winter", "wipe", "wire", "wisdom", "wise",
  "wish", "with", "withdraw", "within", "without", "witness", "woman", "wonder",
  "wonderful", "wood", "wooden", "word", "work", "worker", "working", "workshop",
  "world", "worried", "worry", "worth", "would", "wound", "wrap", "write", "writer",
  "writing", "wrong", "yard", "yeah", "year", "yell", "yellow", "yes", "yesterday",
  "yet", "yield", "you", "young", "your", "yours", "yourself", "youth", "zone",
];

function buildKaoyanItems(): RankedItem[] {
  return KAOYAN_WORDS.map((word, index) => {
    const rank = index + 1;
    return {
      id: `w-${rank}`,
      rank,
      tier: tierForRank(rank, KAOYAN_WORDS.length),
      label: word,
    };
  });
}

const kaoyanTop3000Provider: DataSourceProvider = {
  id: "kaoyan_top3000",
  label: "考研高频词汇（示例集）",
  load: async () => buildKaoyanItems(),
};

const providers = new Map<string, DataSourceProvider>([
  [kaoyanTop3000Provider.id, kaoyanTop3000Provider],
]);

export function getDataSourceProvider(
  id: string
): DataSourceProvider | undefined {
  return providers.get(id);
}

export async function loadDataSourceItems(
  id: string
): Promise<RankedItem[]> {
  const provider = providers.get(id);
  if (!provider) return [];
  return provider.load();
}

export function listDataSources(): DataSourceProvider[] {
  return Array.from(providers.values());
}

export function registerDataSource(provider: DataSourceProvider): void {
  providers.set(provider.id, provider);
}
